apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr                                     # This is the recommended name, but you can change it
  namespace: cpd-instance                             # Replace with the project where you will install Cloud Pak for Data
spec:
  license:
    accept: true
    license: Enterprise                               # Specify the Cloud Pak for Data license you purchased
  storageClass: nfs-managed-storage                   # Replace with the name of a RWX storage class, such as managed-nfs-storage
